version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  app:
    image: blog-api
    ports:
      - "8080:8080"
    depends_on:
      - db