server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog-api-test
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization: false
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: test




#spring.datasource.url=jdbc:postgresql://localhost:5432/blog-api-test
#spring.datasource.username=postgres
#spring.datasource.password=
#spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate properties
#spring.jpa.properties.hibernate.format_sql=true

#spring.jackson.serialization.fail-on-empty-beans=false

#spring.profiles.active=test

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.hibernate.ddl-auto = update